In [1]:
import pandas as pd
import numpy as np
# Creating the customer data table
table = {
    'age': ['<=30', '<=30', '31...40', '>40', '>40', '>40', '31...40', '<=30', '<=30', '>40', '<=30', '31...40', '31...40', '>40'],
    'income': ['high', 'high', 'high', 'medium', 'low', 'low', 'low', 'medium', 'low', 'medium', 'medium', 'medium', 'high', 'medium'],
    'student': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no'],
    'credit_rating': ['fair', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'fair', 'fair', 'excellent', 'excellent', 'fair', 'excellent'],
    'buys_computer': ['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no']
}

dataframe = pd.DataFrame(table)
dataframe

        age  income student credit_rating buys_computer
0      <=30    high      no          fair            no
1      <=30    high      no     excellent            no
2   31...40    high      no          fair           yes
3       >40  medium      no          fair           yes
4       >40     low     yes          fair           yes
5       >40     low     yes     excellent            no
6   31...40     low     yes     excellent           yes
7      <=30  medium      no          fair            no
8      <=30     low     yes          fair           yes
9       >40  medium     yes          fair           yes
10     <=30  medium     yes     excellent           yes
11  31...40  medium      no     excellent           yes
12  31...40    high     yes          fair           yes
13      >40  medium      no     excellent            no

In [2]:
# Calculating the probability of each class

# Calculating the prior probabitity of the class yes
yes_value = dataframe.loc[dataframe['buys_computer'] == 'yes', 'buys_computer'].count() / dataframe.loc[:, 'buys_computer'].count()

# Calculating the prior probability of the class no
no_value = dataframe.loc[dataframe['buys_computer'] == 'no', 'buys_computer'].count() / dataframe.loc[:, 'buys_computer'].count()

print("The prior probabilities of class yes is: ", yes_value)
print("The prior probabilities of class no is: ", no_value)

The prior probabilities of class yes is:  0.6428571428571429
The prior probabilities of class no is:  0.35714285714285715

In [8]:
# Question A2:
# Calculate the class densities of all the features given the various classes

dataframe_age_yes = pd.DataFrame(dataframe.loc[dataframe['buys_computer'] == 'yes', dataframe.columns[[0, 4]]])
dataframe_age_no = pd.DataFrame(dataframe.loc[dataframe['buys_computer'] == 'no', dataframe.columns[[0, 4]]])

# P(<=30|yes)
probability_less_equal_30_given_yes = dataframe_age_yes.loc[dataframe_age_yes['age'] == '<=30', 'age'].count() / dataframe_age_yes.loc[:, 'buys_computer'].count()
print("P(Yes for lessthan 30) = ", probability_less_equal_30_given_yes)
# P(<=30|no)
probability_less_equal_30_given_no = dataframe_age_no.loc[dataframe_age_no['age'] == '<=30', 'age'].count() / dataframe_age_no.loc[:, 'buys_computer'].count()
print("P(No for lessthan 30) = ", probability_less_equal_30_given_no)

# P(31...40|yes)
probability_31_to_40_given_yes = dataframe_age_yes.loc[dataframe_age_yes['age'] == '31...40', 'age'].count() / dataframe_age_yes.loc[:, 'buys_computer'].count()
print("P(Yes for 31 to 40) = ", probability_31_to_40_given_yes)
# P(31...40|no)
probability_31_to_40_no = dataframe_age_no.loc[dataframe_age_no['age'] == '31...40', 'age'].count() / dataframe_age_no.loc[:, 'buys_computer'].count()
print("P(No for 31 to 40) = ", probability_31_to_40_no)

# P(>40|yes)
probability_great_than_40_given_yes = dataframe_age_yes.loc[dataframe_age_yes['age'] == '>40', 'age'].count() / dataframe_age_yes.loc[:, 'buys_computer'].count()
print("P(Yes for greaterthan 40) = ", probability_great_than_40_given_yes)
# P(>40|no)
probability_great_than_40_given_no = dataframe_age_no.loc[dataframe_age_no['age'] == '>40', 'age'].count() / dataframe_age_no.loc[:, 'buys_computer'].count()
print("P(No for greaterthan 40) = ", probability_great_than_40_given_no)

P(Yes for lessthan 30) =  0.2222222222222222
P(No for lessthan 30) =  0.6
P(Yes for 31 to 40) =  0.4444444444444444
P(No for 31 to 40) =  0.0
P(Yes for greaterthan 40) =  0.3333333333333333
P(No for greaterthan 40) =  0.4

In [6]:
# Creating the dataframes for income and class label
income_yes = pd.DataFrame(dataframe.loc[dataframe['buys_computer'] == 'yes', dataframe.columns[[1, 4]]])
income_no = pd.DataFrame(dataframe.loc[dataframe['buys_computer'] == 'no', dataframe.columns[[1, 4]]])

# P(high|yes)
probability_high_given_yes = income_yes.loc[income_yes['income'] == 'high', 'income'].count() / income_yes.loc[:, 'buys_computer'].count()
print("P(high | yes) = ", probability_high_given_yes)
# P(high|no)

probability_high_given_no = income_no.loc[income_no['income'] == 'high', 'income'].count() / income_no.loc[:, 'buys_computer'].count()
print("P(high | no) = ", probability_high_given_no)
# P(medium|yes)
probability_medium_given_yes = income_yes.loc[income_yes['income'] == 'medium', 'income'].count() / income_yes.loc[:, 'buys_computer'].count()
print("P(medium | yes) = ", probability_medium_given_yes)
# P(medium|no)
probability_medium_given_no = income_no.loc[income_no['income'] == 'medium', 'income'].count() / income_no.loc[:, 'buys_computer'].count()
print("P(medium | no) = ", probability_medium_given_no)

# P(low|yes)
probability_low_given_yes = income_yes.loc[income_yes['income'] == 'high', 'income'].count() / income_yes.loc[:, 'buys_computer'].count()
print("P(low | yes) = ", probability_low_given_yes)
# P(low|no)
probability_low_given_no = income_no.loc[income_no['income'] == 'low', 'income'].count() / income_no.loc[:, 'buys_computer'].count()
print("P(low | no) = ", probability_low_given_no)

P(high | yes) =  0.2222222222222222
P(high | no) =  0.4
P(medium | yes) =  0.4444444444444444
P(medium | no) =  0.4
P(low | yes) =  0.2222222222222222
P(low | no) =  0.2

In [12]:
# Creating the dataframes for student and class label
student_yes = pd.DataFrame(dataframe.loc[dataframe['buys_computer'] == 'yes', dataframe.columns[[2, 4]]])
student_no = pd.DataFrame(dataframe.loc[dataframe['buys_computer'] == 'no', dataframe.columns[[2, 4]]])

# P(yes|yes)
probability_yes_given_yes = student_yes.loc[student_yes['student'] == 'yes', 'student'].count() / student_yes.loc[:, 'buys_computer'].count()
print("P(yes | yes) = ", probability_yes_given_yes)
# P(yes|no)
probability_yes_given_no = student_no.loc[student_no['student'] == 'yes', 'student'].count() / student_no.loc[:, 'buys_computer'].count()
print("P(yes | no) = ", probability_yes_given_no)

# P(no|yes)
probability_no_given_yes = student_yes.loc[student_yes['student'] == 'no', 'student'].count() / student_yes.loc[:, 'buys_computer'].count()
print("P(no | yes) = ", probability_no_given_yes)
# P(no|no)
probability_no_given_no = student_no.loc[student_no['student'] == 'no', 'student'].count() / student_no.loc[:, 'buys_computer'].count()
print("P(no | no) = ", probability_no_given_no)

P(yes | yes) =  0.6666666666666666
P(yes | no) =  0.2
P(no | yes) =  0.3333333333333333
P(no | no) =  0.8

In [15]:
# Creating the dataframes for credit rating and class label
credit_rating_yes = pd.DataFrame(dataframe.loc[dataframe['buys_computer'] == 'yes', dataframe.columns[[3, 4]]])
credit_rating_no = pd.DataFrame(dataframe.loc[dataframe['buys_computer'] == 'no', dataframe.columns[[3, 4]]])

# P(excellent|yes)
probability_excellent_given_yes = credit_rating_yes.loc[credit_rating_yes['credit_rating'] == 'excellent', 'credit_rating'].count() / credit_rating_yes.loc[:, 'buys_computer'].count()
print("P(excellent | yes) = ", probability_excellent_given_yes)
# P(excellent|no)
probability_excellent_given_no = credit_rating_no.loc[credit_rating_no['credit_rating'] == 'excellent', 'credit_rating'].count() / credit_rating_no.loc[:, 'buys_computer'].count()
print("P(excellent | no) = ", probability_excellent_given_no)

# P(fair|yes)
probability_fair_given_yes = credit_rating_yes.loc[credit_rating_yes['credit_rating'] == 'fair', 'credit_rating'].count() / credit_rating_yes.loc[:, 'buys_computer'].count()
print("P(fair | yes) = ", probability_fair_given_yes)
# P(fair|no)
probability_fair_given_no = credit_rating_no.loc[credit_rating_no['credit_rating'] == 'fair', 'credit_rating'].count() / credit_rating_no.loc[:, 'buys_computer'].count()
print("P(fair | no) = ", probability_fair_given_no)

P(excellent | yes) =  0.3333333333333333
P(excellent | no) =  0.6
P(fair | yes) =  0.6666666666666666
P(fair | no) =  0.4

In [16]:
# Applying the label encoding each of the features
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
for i in dataframe.columns:
    dataframe[i] = label_encoder.fit_transform(dataframe[i])
dataframe

    age  income  student  credit_rating  buys_computer
0     1       0        0              1              0
1     1       0        0              0              0
2     0       0        0              1              1
3     2       2        0              1              1
4     2       1        1              1              1
5     2       1        1              0              0
6     0       1        1              0              1
7     1       2        0              1              0
8     1       1        1              1              1
9     2       2        1              1              1
10    1       2        1              0              1
11    0       2        0              0              1
12    0       0        1              1              1
13    2       2        0              0              0

In [17]:
# Question A3:
# Finding the correlation between all the features
dataframe.iloc[:, :4].corr(method = 'pearson')

                    age    income       student  credit_rating
age            1.000000  0.414161  8.944272e-02   7.745967e-02
income         0.414161  1.000000  0.000000e+00  -1.980295e-01
student        0.089443  0.000000  1.000000e+00  -6.409876e-17
credit_rating  0.077460 -0.198030 -6.409876e-17   1.000000e+00

In [18]:
# Question A4:
# Apply the Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# Separate features and target variable
X = dataframe.drop('buys_computer', axis=1)
y = dataframe['buys_computer']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
# Applying the naive bayes classifier on customer data
naive_bayes = GaussianNB()
naive_bayes.fit(X_train, y_train)
predicted = naive_bayes.predict(X_test)
accuracy_customer_data = accuracy_score(y_test, predicted)
print("The accuracy of the customer data is: ", accuracy_customer_data)

The accuracy of the customer data is:  0.6666666666666666

In [20]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import preprocessing as prepro 

#Insert your features and labels
samples = np.load('activation_maps_lines_image52_pixel.npy')
features = np.load('activation_maps_lines_image52_labelpixel.npy')

print("The shape of samples and featuresis:\n ",samples.shape,features.shape)
# Reshape your data  (pixels x features)
samples_num = samples.shape[0]   # Total number of pixels
features_num = samples.shape[1]  # Number of features for each pixel
X_reshaped = samples.reshape(samples_num,features_num)
y_reshaped = features.reshape(samples_num)  # Assuming y is your pixel-wise label mask
print(X_reshaped.shape,y_reshaped.shape)

The shape of samples and featuresis:
  (16384, 13) (16384, 1)
(16384, 13) (16384,)

In [21]:
samples = pd.DataFrame(samples,columns=np.arange(0,13))
samples['13']=features # Adding features coulmn into the samples dataset 
samples.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16384 entries, 0 to 16383
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       16384 non-null  float64
 1   1       16384 non-null  float64
 2   2       16384 non-null  float64
 3   3       16384 non-null  float64
 4   4       16384 non-null  float64
 5   5       16384 non-null  float64
 6   6       16384 non-null  float64
 7   7       16384 non-null  float64
 8   8       16384 non-null  float64
 9   9       16384 non-null  float64
 10  10      16384 non-null  float64
 11  11      16384 non-null  float64
 12  12      16384 non-null  float64
 13  13      16384 non-null  uint8
dtypes: float64(13), uint8(1)
memory usage: 1.6 MB

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
# Split the reshaped data into training and testing sets
data_train, data_test, output_train, output_test = train_test_split(X_reshaped, y_reshaped, test_size=0.3, random_state=42)

In [23]:
#train a Naive Bayes classifier
naive_bayes = GaussianNB()
naive_bayes.fit(data_train, output_train)

# Test the accuracy of the Naive Bayes classifier
naive_bayes_accuracy = naive_bayes.score(data_test, output_test)
print(f"Naive Bayes Classifier Accuracy: {naive_bayes_accuracy}")

# If needed, you can also predict on the test set and evaluate other metrics
naive_bayes_predictions = naive_bayes.predict(data_test)

Naive Bayes Classifier Accuracy: 0.15602115541090317